# Generated by Django 6.0.1 on 2026-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_address', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_address', models.CharField(max_length=255)),
                ('package_name', models.CharField(max_length=255)),
                ('package_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='package_photos/')),
                ('status', models.CharField(choices=[('waiting_bus', 'Waiting for package to reach bus station'), ('en_route_campus', 'Package in our van en route to campus'), ('at_campus_hub', 'Package at our campus hub'), ('delivered', 'Package delivered to recipient')], default='waiting_bus', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
